[package]
name = "comfy_make"
version = "0.1.0"
authors = ["Comfy Baguette <MoistBaguette@users.noreply.github.com>"]

[dependencies]
util_kauk_rs = { git = "https://git.comfy.li/rust/util-kauk-rs.git" }
walkdir = "0.1"